### ISSUE TITLE
payjp.js を npm モジュールとしても利用したい

### ISSUE THREAD

**Issue by h-matsuo** [payjp/payjp-node#33]
ブラウザ（クライアント側）用の PAY.JP ライブラリとして [payjp.js](https://pay.jp/docs/payjs) が公開されていますが、
これは `<script>` タグで読み込む形式でしか公開されておらず、npm モジュールとして用いることができません。

しかし、この形式の場合、以下のような課題があると考えます：
- 読み込みタイミングの自前管理が必要となり、シングルページアプリケーションと相性が悪い
- TypeScript 環境でフロントエンドを開発していても型情報が利用できない
- ライブラリバージョンの固定ができない

是非、payjp.js を npm モジュールとしても利用できるように公開を検討いただきたいです。

**Comment by darai0512** [comment]
ご要望ありがとうございました。

申し訳ございませんが、jsライブラリはその性質上、npmモジュールのような自社アプリに組み込んで使うといった形での配布はできません。
加盟店様のDOM上のscriptタグから（クライアントサイドから）弊社ドメインのjsライブラリを読み込む、という形をとることで、加盟店様がPCI-DSSに準拠していること保証しているためです。

参考: https://pay.jp/docs/payjs-guidance

クレジットカードの入力フォームは弊社ドメインのiframe上にある必要がございます。
そのiframeの構築ロジックの都合上、npmにて取り込み加盟店ドメインから配信されたjsではなく、弊社ドメインから配布されたjsが必要となります。
他社のjsライブラリにおきましても、同様の事情からnpmでの配布はされておりません。

SPAへの組み込みにつきましては、他社では特定のSPAフレームワークに対応したnpmモジュールの提供がございますが（ただし内容は、上記の事情の通り、scriptタグを生成するライブラリとなっています）、フレームワークによって記法が異なることもあり、現状は弊社から提供する予定はございません。ただ、実装に関するお問い合わせはいただいており、これが増えるようであれば、モジュールの提供やサンプルの公開など検討したいと思っております。

型情報につきましては、現状は、お手数ですがドキュメントなどを参考にご自身で用意いただければと思います。弊社側も需要は認識しており、型情報ファイルの提供は検討しております。

バージョンにつきましては、常に最新版が利用される仕組みになっておりますのでご安心ください。
